import {
  svgCpp,
  svgCppBig,
  svgCSharp,
  svgCSharpBig,
  svgCSS,
  svgCSSBig,
  svgFirebase,
  svgFirebaseBig,
  svgGitHub,
  svgGitHubBig,
  svgHTML,
  svgHTMLBig,
  svgJava,
  svgJavaBig,
  svgJS,
  svgJSBig,
  svgMySQL,
  svgMySQLBig,
  svgNextAuth,
  svgNextAuthBig,
  svgNextIntl,
  svgNextIntlBig,
  svgNextjs,
  svgNextjsBig,
  svgNodeJS,
  svgNodeJSBig,
  svgPython,
  svgPythonBig,
  svgReactjs,
  svgReactjsBig,
  svgSanity,
  svgSanityBig,
  svgTailwindCSS,
  svgTailwindCSSBig,
  svgTypeScrip,
  svgTypeScripBig,
} from "@/components/svgPaths";

export const skillsArray = [
  {
    name: "HTML",
    theSvg: svgHTML,
    bigSvg: svgHTMLBig,
    mastery: 1,
  },
  {
    name: "CSS",
    theSvg: svgCSS,
    bigSvg: svgCSSBig,
    mastery: 1,
  },
  {
    name: "JavaScript",
    theSvg: svgJS,
    bigSvg: svgJSBig,
    mastery: 1,
  },
  {
    name: "TypeScript",
    theSvg: svgTypeScrip,
    bigSvg: svgTypeScripBig,
    mastery: 1,
  },
  {
    name: "React.js",
    theSvg: svgReactjs,
    bigSvg: svgReactjsBig,
    mastery: 1,
  },
  {
    name: "Next.js",
    theSvg: svgNextjs,
    bigSvg: svgNextjsBig,
    mastery: 1,
  },
  {
    name: "GitHub",
    theSvg: svgGitHub,
    bigSvg: svgGitHubBig,
    mastery: 1,
  },
  {
    name: "Tailwind CSS",
    theSvg: svgTailwindCSS,
    bigSvg: svgTailwindCSSBig,
    mastery: 1,
  },
  {
    name: "Node.js",
    theSvg: svgNodeJS,
    bigSvg: svgNodeJSBig,
    mastery: 1,
  },
  {
    name: "next-intl",
    theSvg: svgNextIntl,
    bigSvg: svgNextIntlBig,
    mastery: 1,
  },
  {
    name: "MySQL",
    theSvg: svgMySQL,
    bigSvg: svgMySQLBig,
    mastery: 0.8,
  },
  {
    name: "Firebase",
    theSvg: svgFirebase,
    bigSvg: svgFirebaseBig,
    mastery: 0.8,
  },
  {
    name: "NextAuth.js",
    theSvg: svgNextAuth,
    bigSvg: svgNextAuthBig,
    mastery: 0.8,
  },
  {
    name: "Sanity (CMS)",
    theSvg: svgSanity,
    bigSvg: svgSanityBig,
    mastery: 0.7,
  },
  {
    name: "Java",
    theSvg: svgJava,
    bigSvg: svgJavaBig,
    mastery: 0.6,
  },
  {
    name: "Python",
    theSvg: svgPython,
    bigSvg: svgPythonBig,
    mastery: 0.6,
  },
  {
    name: "C#",
    theSvg: svgCSharp,
    bigSvg: svgCSharpBig,
    mastery: 0.6,
  },
  {
    name: "C++",
    theSvg: svgCpp,
    bigSvg: svgCppBig,
    mastery: 0.6,
  },
];
