export const experienceContent = [
  {
    company: "HalaDD",
    job: "Software Engineer",
    jobAr: "مهندس برمجيات",
    start: "November 2024",
    startAr: "نوفمبر 2024",
    end: "July 2025",
    endAr: "يوليو 2025",
    address: "Al-Dayiaa, Kuwait",
    addressAr: "الدعية، الكويت",
    content1: `<ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Built two enterprise-grade platforms: a multilingual e-commerce storefront and a full-featured admin system.</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Developed responsive UIs using <strong>Next.js</strong>, <strong>TypeScript</strong>, and <strong>Tailwind CSS</strong>, with SSR/ISR, routing, reusable components, and dark/light themes.</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Created admin pages for managing users, contracts, and reports; implemented customer-facing store with filters, checkout, and order tracking in English and Arabic.</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Integrated <strong>Firebase Auth</strong>, <strong>Storage</strong>, and <strong>MySQL</strong>; implemented secure APIs, role-based access, and smart filtering.</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Added performance optimizations (e.g., <strong>react-window</strong>, <strong>Framer Motion</strong>, <strong>Recharts</strong>, <strong>sweetalert2</strong>) and real-time features like SMS updates and print-ready views.</li></ol>`,
    content1Ar: `<ol><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>طوّرت منصتين على مستوى المؤسسات: متجر إلكتروني متعدد اللغات ونظام إدارة متكامل.</li><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>أنشأت واجهات مستخدم متجاوبة باستخدام <strong>Next.js</strong> و<strong>TypeScript</strong> و<strong>Tailwind CSS</strong>، مع دعم SSR وISR وتبديل الوضع الليلي/النهاري.</li><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>صممت لوحة تحكم لإدارة العملاء والعقود والتقارير، إضافة إلى متجر للعملاء يشمل التصفية، الدفع، وتتبع الطلبات باللغتين العربية والإنجليزية.</li><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>دمجت خدمات <strong>Firebase</strong> (المصادقة، التخزين) و<strong>MySQL</strong>، مع تنفيذ API آمنة ونظام صلاحيات ذكي.</li><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>حسّنت الأداء عبر أدوات مثل <strong>react-window</strong> و<strong>Framer Motion</strong>، وأضفت مخططات بيانية (<strong>Recharts</strong>) وتنبيهات تفاعلية (<strong>sweetalert2</strong>).</li></ol>`,
    content2: "Link to the website:",
    content2Ar: "رابط الموقع:",
    link1: "https://www.haladd.com",
    link1Name: "HalaDD",
  },
  {
    company: "Applai Teknoloji",
    job: "Software Engineer",
    jobAr: "مهندس برمجيات",
    start: "February 2024",
    startAr: "فبراير 2024",
    end: "May 2024",
    endAr: "مايو 2024",
    address: "Beylikdüzü, İstanbul",
    addressAr: "بيليك دوزو، اسطنبول",
    content1: `<ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Built web scrapers with <strong>Python</strong> (BeautifulSoup) and <strong>Puppeteer</strong> to extract and structure e-commerce data.</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Upgraded a legacy auction site with <strong>Next.js</strong>, <strong>Tailwind CSS</strong>, and <strong>TypeScript</strong>, improving UX and performance.</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Created a listings platform for cars/electronics/real estate with multilingual support, real-time updates, and secure forms.</li></ol>`,
    content1Ar: `<ol><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>طوّرت أدوات استخراج بيانات (web scraping) باستخدام <strong>Python</strong> و<strong>Puppeteer</strong> لجمع بيانات من مواقع التجارة الإلكترونية.</li><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>حدّثت موقع مزادات قديم إلى نسخة حديثة باستخدام <strong>Next.js</strong> و<strong>Tailwind CSS</strong> و<strong>TypeScript</strong>، مما حسّن الأداء وتجربة المستخدم.</li><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>أنشأت منصة إعلانات لمنتجات مثل السيارات والعقارات مع دعم تعدد اللغات، التحديثات اللحظية، ونظام مصادقة آمن.</li></ol>`,
    content2: "Links to the websites:",
    content2Ar: "روابط المواقع:",
    link1: "https://mazzadak-demo.vercel.app",
    link1Name: "Mazzadak",
    link2: "https://matloop-demo.vercel.app",
    link2Name: "Matloop",
  },
  {
    company: "3QDigital",
    job: "Front-end Developer",
    jobAr: " تطوير الواجهة الأمامية للمواقع",
    start: "October 2023",
    startAr: "أكتوبر 2023",
    end: "December 2023",
    endAr: "ديسمبر 2023",
    address: "Beylikdüzü, İstanbul",
    addressAr: "بيليك دوزو، اسطنبول",
    content1: `<ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Built multilingual, mobile-friendly marketing websites with <strong>Next.js</strong>, <strong>TypeScript</strong>, <strong>Tailwind CSS</strong>, and <strong>NextAuth.js</strong>.</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Collaborated on GitHub; participated in code reviews and UI iterations to meet client goals.</li></ol>`,
    content1Ar: `<ol><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>ساهمت في تطوير مواقع تعريفية لشركات استثمارية باستخدام <strong>Next.js</strong> و<strong>TypeScript</strong> و<strong>NextAuth.js</strong> لدعم الترجمة والمصادقة.</li><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>عملت ضمن فريق باستخدام GitHub، وشاركت في مراجعة الشيفرات وتحسين الواجهات.</li></ol>`,
    // content2: "Some of the websites that I contributed to or fully developed:",
    // content2Ar: "مواقع ساهمت في تطويرها أو طورتها بالكامل:",
    // link1: "https://www.amwalelmaleh.com",
    // link1Name: "AmwalElmaleh",
    // link2: "https://www.almutahde.com",
    // link2Name: "Al-mutahde",
    // link3: "https://www.eltaawon.com",
    // link3Name: "El-taawon",
  },
  {
    company: "Noonmar",
    job: "Software Engineer",
    jobAr: "مهندس برمجيات",
    start: "September 2022",
    startAr: "سبتمبر 2022",
    end: "November 2022",
    endAr: "نوفمبر 2022",
    address: "Şirinevler, İstanbul",
    addressAr: "شيرينفلر، اسطنبول",
    content1: `<ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Led strategic meetings to explore upgrading an e-commerce site to a marketplace model.</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Delivered feasibility reports with clear technical and financial insights to stakeholders.</li></ol>`,
    content1Ar: `<ol><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>أدرت اجتماعات استراتيجية لدراسة تحويل موقع تجارة إلكترونية إلى سوق إلكتروني شامل.</li><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>أعددت تقارير شاملة حول الجوانب التقنية والمالية لدعم اتخاذ القرار.</li></ol>`,
  },
  {
    company: "Üsküdar University",
    job: "Graduation Project",
    jobAr: "مشروع التخرج",
    start: "March 2023",
    startAr: "مارس 2023",
    end: "June 2023",
    endAr: "يونيو 2023",
    address: "Üsküdar, İstanbul",
    addressAr: " أوسكودار، اسطنبول",
    content1: `<ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Built a performant e-commerce site with <strong>Next.js 13</strong>, <strong>TypeScript</strong>, <strong>Tailwind CSS</strong>, and <strong>Sanity CMS</strong>.</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Integrated secure auth via <strong>NextAuth.js</strong> (Google and email/password).</li></ol>`,
    content1Ar: `<ol><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>أنشأت موقع تجارة إلكترونية باستخدام <strong>Next.js 13</strong> و<strong>TypeScript</strong> و<strong>Tailwind CSS</strong> ودمجت <strong>Sanity CMS</strong> لإدارة المحتوى.</li><li data-list="bullet" class="ql-align-right"><span class="ql-ui" contenteditable="false"></span>أضفت نظام مصادقة آمن باستخدام <strong>NextAuth.js</strong> مع دعم تسجيل الدخول عبر Google والبريد الإلكتروني.</li></ol>`,
    content2: "Link to the website:",
    content2Ar: "رابط الموقع:",
    link1: "https://eshop-responsive-website.vercel.app",
    link1Name: "e-shop",
  },
];
