export const experienceContent = [
  {
    company: "Applai Teknoloji",
    job: "Software Engineer",
    jobAr: "مهندس برمجيات",
    start: "February 2024",
    startAr: "فبراير 2024",
    end: "May 2024",
    endAr: "مايو 2024",
    address: "Beylikdüzü, İstanbul",
    addressAr: "بيليك دوزو، اسطنبول",
    content1:
      "I am adept at web scraping, utilizing Python Beautiful Soup and JavaScript Puppeteer to extract product data from an e-commerce site via category links, and storing the information in Excel files. I also served as a quality assurance engineer for a PHP auction website, modernizing it with Next.js, Tailwind, and TypeScript for enhanced functionality and aesthetics. Furthermore, I developed a dynamic website enabling users to post needs for cars, electronics, real estate, or jobs using Next.js, Next-intl, Tailwind, TypeScript, and Firebase, implementing features such as user authentication and real-time updates for improved usability.",
    content1Ar:
      "أتقن مهارة استخراج المعلومات من الويب، حيث استخدمت أدوات مثل Python Beautiful Soup و JavaScript Puppeteer لاستخراج بيانات المنتجات من موقع تجارة إلكترونية عبر روابط الفئات، مع تخزين هذه المعلومات في ملفات Excel. بالإضافة إلى ذلك، عملت كمهندس ضمان الجودة لموقع مزادات PHP، حيث قمت بتحديثه باستخدام تقنيات حديثة مثل Next.js و Tailwind و TypeScript لتحسين الوظائف والجماليات.علاوة على ذلك، قمت ببناء موقع ويب ديناميكي يتيح للمستخدمين نشر احتياجاتهم من سيارات أوإلكترونيات أو عقارات أو وظائف باستخدام تقنيات متطورة مثل Next.js و Next-intl و Tailwind و TypeScript و Firebase، مع تنفيذ ميزات مثل المصادقة للمستخدم والتحديثات الفورية لتحسين تجربة المستخدم.",
    content2: "Links to the websites:",
    content2Ar: "روابط المواقع:",
    link1: "https://mazzadak-demo.vercel.app",
    link1Name: "Mazzadak",
    link2: "https://matloop-demo.vercel.app",
    link2Name: "Matloop",
  },
  {
    company: "3QDigital",
    job: "Front-end Developer",
    jobAr: " تطوير الواجهة الأمامية للمواقع",
    start: "October 2023",
    startAr: "أكتوبر 2023",
    end: "December 2023",
    endAr: "ديسمبر 2023",
    address: "Beylikdüzü, İstanbul",
    addressAr: "بيليك دوزو، اسطنبول",
    content1:
      "I contributed to the development of informational websites for trading companies, focusing on fostering investment interest. Leveraging technologies such as Next.js, Tailwind CSS, JavaScript, NextAuth.js (for authentication), next-intl (for translation), and TypeScript, I actively participated in the projects through collaborative development on GitHub. My contributions played a key role in bringing these websites to fruition.",
    content1Ar:
      "ساهمت في تطوير المواقع المعلوماتية للشركات التجارية مع التركيز على تعزيز الاهتمام الاستثماري. من خلال الاستفادة من تقنيات مثل Next.js وTailwind CSS وJavaScript وNextAuth.js (للمصادقة) وnext-intl (للترجمة) وTypeScript، شاركت بنشاط في المشاريع من خلال التطوير التعاوني على GitHub. لعبت مساهماتي دورًا رئيسيًا في تحقيق هذه المواقع.",
    // content2: "Some of the websites that I contributed to or fully developed:",
    // content2Ar: "مواقع ساهمت في تطويرها أو طورتها بالكامل:",
    // link1: "https://www.amwalelmaleh.com",
    // link1Name: "AmwalElmaleh",
    // link2: "https://www.almutahde.com",
    // link2Name: "Al-mutahde",
    // link3: "https://www.eltaawon.com",
    // link3Name: "El-taawon",
  },
  {
    company: "Noonmar",
    job: "Software Engineer",
    jobAr: "مهندس برمجيات",
    start: "September 2022",
    startAr: "سبتمبر 2022",
    end: "November 2022",
    endAr: "نوفمبر 2022",
    address: "Şirinevler, İstanbul",
    addressAr: "شيرينفلر، اسطنبول",
    content1:
      "In a previous role, I conducted and reported on meetings to evaluate the viability of upgrading an e-commerce website into a marketplace. As the facilitator, I guided discussions among stakeholders, ensuring a thorough exploration of technical and financial requirements. I compiled detailed reports summarizing the discussions, conclusions, and actionable recommendations, providing decision-makers with valuable insights for informed decision-making. This experience enhanced my skills in meeting facilitation, information synthesis, and delivering concise reports to support strategic decisions.",
    content1Ar:
      "في دور سابق، قمت بتنظيم وتقديم تقارير حول اجتماعات لتقييم جدوى ترقية موقع تجارة إلكترونية إلى سوق عبر الإنترنت. بصفتي الميسر، قمت بتوجيه المناقشات بين الفاعلين، ضمنت استكشافًا شاملاً للمتطلبات التقنية والمالية. جمعت تقارير مفصلة تلخص المناقشات والاستنتاجات والتوصيات القابلة للتنفيذ، مما قدم لصناع القرار رؤى قيمة لاتخاذ قرارات مستنيرة. عززت هذه التجربة مهاراتي في تيسير الاجتماعات وتوليف المعلومات وتقديم تقارير موجزة لدعم القرارات الاستراتيجية.",
  },
  {
    company: "Üsküdar University",
    job: "Graduation Project",
    jobAr: "مشروع التخرج",
    start: "March 2023",
    startAr: "مارس 2023",
    end: "June 2023",
    endAr: "يونيو 2023",
    address: "Üsküdar, İstanbul",
    addressAr: " أوسكودار، اسطنبول",
    content1:
      "I developed an e-commerce website utilizing the most recent version of the React.js library, specifically Next.js 13. Employing Tailwind CSS for styling the website, I employed Typescript, a superset of Javascript, to implement the website's functionality. For content management, I integrated Sanity.io into the platform. To ensure robust security in user authentication, I implemented NextAuth, incorporating both Google and Credentials as authentication providers.",
    content1Ar:
      "طوّرت موقع تجارة الكترونية باستخدام أحدث إصدار من مكتبة React.js، وتحديداً Next.js 13. استخدمت Tailwind CSS لتنسيق التصميم الخاص بالموقع، وإستفدت من Typescript، الذي يعتبر تفرعًا متقدمًا من Javascript، لتطوير وظائف الموقع. لإدارة المحتوى، قمت بدمج Sanity.io في النظام. من أجل ضمان أمان قوي للمستخدم، قمت بإستخدام NextAuth مع دمج كل من Google وCredentials كخياري إنشاء حساب و تسجيل دخول.",
    content2: "Link to the website:",
    content2Ar: "رابط الموقع:",
    link1: "https://eshop-responsive-website.vercel.app",
    link1Name: "e-shop",
  },
];
